### ISSUE TITLE
Fuego connection sporadically goes down

### ISSUE THREAD

**Issue by jflowers45** [niemanlab/openfuego#24]
Hi all,
  We've had a fuego instance running for several months now.  From time to time the collector seems to stop writing new info to disk and we have to kill both processes (or just one, if it died) and restart.

Most recently, even a restart of the processes didn't do the trick on our main fuego instance.  We have other instances (for example on our staging server) that we don't always run but that we can still start up without issue.

I was wondering if anyone has run into this or any other flavors of connection issues with Twitter via fuego- I'm thinking Twitter blocked our IP, but I don't know for sure and will probably need to dig into the stream connection code to find out.

**Comment by jflowers45** [comment]
it turns out twitter streaming api doesn't like clock drift ...

https://twittercommunity.com/t/streaming-api-with-oauth-was-working-fine-now-returning-401-unauthorized-error/7550/4

fixed it with sudo ntpdate ntp.ubuntu.com

**Comment by adamjmartin** [comment]
👍🏽👍🏽👍🏽
